server:
  port: 8080

zuul:
  routes:
    auth-center:
      path: /login/**
      url: http://auth-center:8081/
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false

    user-app:
      path: /api/v1/user/**
      url: http://user-app:8082/

shuaicj.security.jwt.secret: otherpeopledontknowit
