boomaker:
  endpoint:
    http://lines.bookmaker.eu/
bovada:
  endpoint:
    https://www.bovada.lv/services/sports/event/v2/events/A/description/football/nfl
   
    
server:
  port: 8080
spring:
  redis:
    port: 6379
    host: localhost

logging:
  level:
    org.springframework.web: DEBUG
    
api:
  version:
    v1