
spring:
  security:
    user:
      name: password
      password: password
      roles:
        - ACTUATOR
  datasource:
#   ?currentSchema=hagrid
    url: jdbc:postgresql://localhost:5432/pick-5-postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  output:
    ansi:
      enabled: ALWAYS
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'
    enabled-by-default: true
 
oauth:
  keyfile:
    private: private_key.priv
    public: public_key.pub
