export const NAME = 'organization'


/*
	CREATE ORGANIZATION
*/

export const CREATE_ORGANIZATION = `${NAME}/CREATE_ORGANIZATION`
export const CREATE_ORGANIZATION_SUCCESS = `${NAME}/CREATE_ORGANIZATION_SUCCESS`
export const CREATE_ORGANIZATION_FAILURE = `${NAME}/CREATE_ORGANIZATION_FAILURE`