server:
  port: 8003

spring:
  application:
    name: registration-app
  management:
        endpoint:
            health:
                show-details: always
  endpoints:
        web:
            exposure:
                include: '*'

version:
  "/api/v1"

app:
  path: 
    email-send:
      "email-app/${version}/email/" 
    user-save: 
      "user-app/${version}/user/save/"

routes:
  register:
    "${version}/register"